### PR TITLE
update transition for kolibri as well as exercise-perseus-r…

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Review by indirectlylit — COMMENTED** [review]
Hey, thanks for the PR. Are the animations working as expected for you though? I'm seeing issues with both the exercise viz and the coach table:

* exercise viz, new icons slide in from the right
* coach table, now just seems to show a single item?

**Comment by 66eli77** [comment]
Yes, the exercise issue is related to the key attribute requirement for
transition-group I mentioned earlier.
I will test the coach report issue tomorrow.

**Comment by indirectlylit** [comment]
In https://github.com/learningequality/kolibri/pull/741:

* merged in these changes
* merged in latest vue2 branch
* fixed bugs discussed above
* remove search pane transitions, however the layout is still broken for other reasons - don't know when that happened

**Comment by indirectlylit** [comment]
see https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/25

**Pull request merged**
